apiVersion: apps/v1
kind: Deployment
metadata:
  name: plots-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vikky295/plots-backedn:1.3   # ensure this image is pushed to a container registry accessible by AKS
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "plots-postgres"  # <-- updated to match your Postgres service name
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "plots_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          # Optionally add resource requests/limits as needed
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"



