apiVersion: apps/v1
kind: Deployment
metadata:
  name: plots-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vikky295/plots-frontend:4.2 # ensure this image is pushed to an accessible registry
          ports:
            - containerPort: 80
          # Optionally add resource requests/limits
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"

 

