---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plots-postgres
  labels:
    app: plots-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plots-postgres
  template:
    metadata:
      labels:
        app: plots-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "plots_db"
        - name: POSTGRES_USER
          value: "viksur"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: plots-postgres
  labels:
    app: plots-postgres
spec:
  selector:
    app: plots-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plots-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi